apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: flight-data
  labels:
    app: flight-api
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight-api
  template:
    metadata:
      labels:
        app: flight-api
        version: v2
    spec:
      containers:
      - name: api
        image: flight-collector-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
          name: http
        - containerPort: 9090
          name: metrics
        envFrom:
        - configMapRef:
            name: flight-data-config
        - secretRef:
            name: flight-data-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v2/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v2/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: flight-data-pvc
      - name: logs-volume
        emptyDir: {}