apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: flight-data
  labels:
    app: flight-api
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: flight-api
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-nodeport
  namespace: flight-data
  labels:
    app: flight-api
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
    nodePort: 30001
  selector:
    app: flight-api