name: Collect Flight Data

on:
  schedule:
    - cron: '55 4 * * *'  # 11:55 PM EST (4:55 UTC)
    - cron: '0 14 * * *'  # 6 AM PST (14:00 UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect-yyz-data:
    runs-on: ubuntu-latest
    if: github.event.schedule == '55 4 * * *' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Collect YYZ Data
      run: npm run collect:yyz
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

  collect-sfo-data:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 14 * * *' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Collect SFO Data
      run: npm run collect:sfo
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}